[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bengrn"
version = "1.0.6"
description = "benchmarking gene regulatory networks"
authors = [ "jkobject",]
readme = "README.md"
keywords = [ "scRNAseq", "GRN", "gene regulatory networks", "benchmark", "comp bio", "scPRINT",]

[tool.poetry.dependencies]
python = "3.10.*"
anndata = "*"
scipy = "*"
scikit-learn = "*"
numpy = "*"
arboreto = "*"
pyscenic = "*"
ctxcore = "*"
seaborn = "*"
decoupler = "*"
pandas = ">=2.0.0"
grnndata = "*"
omnipath = "*"
dask-expr = "*"

[tool.poetry.extras]
dev = [ "pytest", "coverage", "flake8", "black", "toml", "isort", "pytest-cov", "mypy", "gitchangelog", "mkdocs", "mkdocs-git-revision-date-localized-plugin", "mkdocstrings", "mkdocs-git-authors-plugin", "mkdocs-jupyter", "mkdocstrings-python",]

[tool.poetry.scripts]
bengrn = "bengrn.__main__:main"

[tool.poetry.dependencies.pytest]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.coverage]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.flake8]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.black]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.isort]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.pytest-cov]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.mypy]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.gitchangelog]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.mkdocs]
version = "1.0.6"
optional = true

[tool.poetry.dependencies.toml]
version = "1.0.6"
optional = true
